domain_randomization:
  lighting:
    enabled: true
    position_range_low: [0.5, -0.001, -0.1]
    position_range_high: [1.0, 0.001, -0.05]
    diffuse_range:
      low: [0.4, 0.4, 0.4]
      high: [0.5, 0.5, 0.5]
    ambient_range:
      low: [0.4, 0.4, 0.4]
      high: [0.5, 0.5, 0.5]
    specular_range:
      low: [0.4, 0.4, 0.4]
      high: [0.8, 0.8, 0.8]
    intensity_range: [0.8, 1.5]

  action_scale:
    enabled: false
    pos_scale_range: [0.008, 0.012]
    rot_scale_range: [0.18, 0.3]

  robot_pose:
    enabled: true
    position_range_low: [-0.1, -0.2, 0.00]
    position_range_high: [0.05, -0.1, 0.20]
    rotation_enabled: true
    angle_range: [-0.5, 0.5]
    yaw_only: false

  cameras:
    enabled: false
    front:
      position_noise_low: [-0.05, -0.05, -0.02]
      position_noise_high: [0.05, 0.05, 0.02]
      quat_noise_range: [-0.02, 0.02]
    wrist1:
      quat_noise_range: [-0.02, 0.02]
    wrist2:
      quat_noise_range: [-0.02, 0.02]


  floor:
    enabled: false

  skybox:
    enabled: true

  strawberry_texture:
    enabled: true

  leaf_texture:
    enabled: true

  vine_color:
    enabled: true

  objects_count:
    enabled: true
    fruit_xmls: ["strawb_stiff.xml", "strawb_fork.xml", "strawb_fork_double.xml"]
    leaf_xmls: ["leaves.xml"]
    min_fruits: 4
    max_fruits: 8
    min_leaves: 4
    max_leaves: 6
    max_ripe: 5
    random_count: True

  strawberry_mesh:
    enabled: true
    mesh_pool: ["sb_1", "sb_2", "sb_3", "sb_4", "sb_5"]

  calyx_mesh:
    enabled: true
    mesh_pool: ["calyx_1", "calyx_2", "calyx_3", "calyx_4", "calyx_5"]

  leaf_mesh:
    enabled: true
    mesh_pool: ["leaf_1", "leaf_2", "leaf_3", "leaf_4", "leaf_5"]

  object_positions:
    enabled: true
    rotation_enabled: true
    yaw_only: False
    rotation_angle_range: [-0.05, 0.05]
    position_range_low: [-0.06, -0.1, -0.02]
    position_range_high: [0.06, 0.1, 0.02]

  object_scale:
    enabled: true
    fruit_scale_range: [0.5, 1.4]
    leaf_scale_range: [0.2, 0.45]

