domain_randomization:
  hard_mode:
    enabled: true
    p: 0.1
    name_match: "fruit"    
    ripe_materials: ["r1", "r2", "r3"]
    unripe_materials: ["u1", "u2", "u3", "g1", "g2", "g3"]


  lighting:
    enabled: true
    position_range_low: [-0.8, -0.5, -0.05]
    position_range_high: [1.2, 0.5, 0.2]
    diffuse_range:
      low: [0.05, 0.05, 0.05]
      high: [0.3, 0.3, 0.3]
    ambient_range:
      low: [0.0, 0.0, 0.0]
      high: [0.2, 0.2, 0.2]
    specular_range:
      low: [0.0, 0.0, 0.0]
      high: [0.5, 0.5, 0.5]
    intensity_range: [0.1, 1.0]

  action_scale:
    enabled: true
    pos_mult: 0.3
    rot_mult: 0.3

  robot_pose:
    enabled: true
    position_range_low: [-0.04, -0.1, 0.00]
    position_range_high: [0.04, 0.1, 0.10]
    rotation_enabled: true
    angle_range: [-0.5, 0.5]
    yaw_only: false

  camera_pose:
    enabled: true
    position_range_low: [-0.005, -0.005, -0.005]
    position_range_high: [0.005, 0.005, 0.005]
    rotation_enabled: true
    angle_range: [-0.01, 0.01]
    yaw_only: false

  table:
    enabled: true
    position_range_low: [-0.05, -0.02, -0.05]
    position_range_high: [0.08, 0.02, 0.05]
    p_absent: 0.5

  floor:
    enabled: true

  skybox:
    enabled: true

  strawberry_texture:
    enabled: true

  leaf_texture:
    enabled: true

  vine_color:
    enabled: true

  objects_count:
    enabled: true
    fruit_xmls: ["strawb_stiff.xml", "strawb_fork.xml", "strawb_fork_double.xml"]
    leaf_xmls: ["leaves.xml"]
    min_fruits: 7
    max_fruits: 11
    min_leaves: 4
    max_leaves: 8
    max_ripe: 5
    random_count: True

  strawberry_mesh:
    enabled: true
    mesh_pool: ["sb_1", "sb_2", "sb_3", "sb_4", "sb_5"]

  calyx_mesh:
    enabled: true
    mesh_pool: ["calyx_1", "calyx_2", "calyx_3", "calyx_4", "calyx_5"]

  leaf_mesh:
    enabled: true
    mesh_pool: ["leaf_1", "leaf_2", "leaf_3", "leaf_4", "leaf_5"]

  object_positions:
    enabled: true
    rotation_enabled: true
    yaw_only: False
    rotation_angle_range: [-0.08, 0.08]
    position_range_low: [-0.1, -0.18, -0.25]
    position_range_high: [0.15, 0.18, 0.1]

  object_scale:
    enabled: true
    fruit_scale_range: [0.5, 1.4]
    leaf_scale_range: [0.2, 0.45]

